version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - path.data=/app/data
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${LS6_OPENSEARCH_DATA_PATH}:/app/data

volumes:
  opensearch_data:
    driver: local