version: '3.8'

services:
  elasticsearch:
    image: ls6-elasticsearch-image
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - path.data=/usr/share/elasticsearch/data
      - path.logs=/usr/share/elasticsearch/logs
    volumes:
      - ${ES_DATA_DIR}:/usr/share/elasticsearch/data
      - ${ES_LOG_DIR}:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
    networks:
      - ls6-network

  fscrawler:
    image: ls6-fscrawler-image
    container_name: fscrawler
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ${FILE_SCAN_DIR}:/tmp/es:ro
    depends_on:
      - elasticsearch
    networks:
      - ls6-network

  web:
    image: ls6-web-image
    container_name: web
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ${FILE_SCAN_DIR}:/app/static/files:ro
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - ls6-network

  suggestions:
    image: ls6-suggestions-image
    container_name: suggestions
    ports:
      - "5001:5000"
    networks:
      - ls6-network

volumes:
  esdata:
  eslogs:

networks:
  ls6-network:
    driver: bridge
