version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"