version: '3'

services:
  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 9200:9200
    volumes:
      - ${LS6_ELASTICSEARCH_DATA_PATH}:/usr/share/elasticsearch/data

volumes:
  elasticsearch_data:
    driver: local