# Используем официальный образ Elasticsearch версии 7.14.1
FROM elasticsearch:7.14.1

# Копируем файл конфигурации Elasticsearch, если он есть (опционально)
# COPY elasticsearch.yml /usr/share/elasticsearch/config/

# Устанавливаем переменные среды для указания путей к данным и логам (если требуется)
# ENV path.data=/usr/share/elasticsearch/data
# ENV path.logs=/usr/share/elasticsearch/logs

# Открываем порты, если это необходимо (опционально, так как базовый образ уже открывает порт 9200)
# EXPOSE 9200
# EXPOSE 9300
